package sk.stu.fiit.flexemvavaprojekt.router;

public enum RouterEnum {
    LOGINVIEW,CVICENECPLANVIEW,CVICENECRECENZIAVIEW,CVICENECPROFILVIEW,RECEPCNAEVIDENCIAVIEW,
    RECEPCNANOVYCLENVIEW,RECEPCNAPROFILVIEW,RECEPCNARECENZIAVIEW,RECEPCNANOVYTRENERVIEW
}